"""
TESTS is a dict with all you tests.
Keys for this will be categories' names.
Each test is dict with
    "input" -- input data for user function
    "answer" -- your right answer
    "explanation" -- not necessary key, it's using for additional info in animation.
"""

TESTS = {
    "Basics": [
        {
            "input": ['DONTWORRYBEHAPPY', 'FVRVGWFTFFGRIDRF', 'DLLCZXMFVRVGWFTF'],
            "answer": "BEHAPPYDONTWORRY",
            "explanation": "CHECKIO",
        },
        {
            "input": ['HELLO', 'OIWWC', 'ICP'],
            "answer": "BYE",
            "explanation": "HELLO",
        },
        {
            "input": ['LOREMIPSUM', 'OCCSDQJEXA', 'OCCSDQJEXA'],
            "answer": "LOREMIPSUM",
            "explanation": "DOLORIUM",
        },

    ],
    "Extra": [
        {
            "input": ['ANDNOWFORSOMETHINGCOMPLETELYDIFFERENT', 'PLWUCJUMKZCZTRAPBTRMFWZRICEFRVUDXYSAI',
                      'XKTSIZQCKQOPZYGKWZDIBZZRTNTSZAXEAAOASGPVFXPJEKOLXANARBLLMYSRHGLRWCPLWQIZEGEPYRIMIYSFHUBSRSAMPLFFXNNACALMFLBFRJHAVVCETURUPLZHFBJLWPBOPPL'],
            "answer": "IMALUMBERJACKANDIMOKISLEEPALLNIGHTANDIWORKALLDAYICUTDOWNTREESISKIPANDJUMPILIKETOPRESSWILDFLOWERSIPUTONWOMENSCLOTHINGANDHANGAROUNDINBARS",
            "explanation": "PYTHON",
        },
        {
            "input": ['ANODSASGOODASAWINKTOABLINDBATEH', 'MBBWQMGTHMPOFTUUBXMMMPYBLPPNMCT',
                      'TSFGMFHUXKQGFBYTVRLYHSERLMITARKPBR'],
            "answer": "HESNOTTHEMESSIAHHESAVERYNAUGHTYBOY",
            "explanation": "MONTY",
        },
        {
            "input": ["DOESNOTWORKINALLCASES", "RVSZBVLKQFYTBHZSQHKSU",
                      "VLFLOUWLCADWSVTHPYGYGBQLGL"],
            "answer": "HEREANEXAMPLEOFABROKENCASE",
            "explanation": "OHOHOHSOCOOL",
        },

        {
            "input": [
                'ITSNOTPININGITSPASSEDONTHISPARROTISNOMOREITHASCEASEDTOBEITSEXPIREDANDGONETOMEETITSMAKERTHISISALATEPARROTITSASTIFFBEREFTOFLIFEITRESTSINPEACEIFYOUHADNTNAILEDITTOTHEPERCHITWOULDBEPUSHINGUPTHEDAISIESITSRUNGDOWNTHECURTAINANDJOINEDTHECHOIRINVISIBLETHISISANEXPARROT',
                'ONAQCZJQQWTAQWGVUAVSJIVWVOMXDFXIBLGTIURFKCBKOYWMDGKXBRPKCBVSDJQUSJUVGUUHMWCSYMWWZMUDYKLBKWYCADZGNMSOXLWWWZMIVHOZNESXYNWCLFQISONZHGZMQQDKUKHWLSWXVGXVWBGCTHRONBRHNYXHFIBQWKUOTGPKJCVVOHOXDZBMGOOMQHGONAUITALRKTNPHQALBDWTUVGXUCVHRZBMFVUCZLBBCALPRYBKWYCADBKRXDFXIB',
                'GFTUWMBBDZRLQJVZVCWOVUZWTXIUESZNMUGGHQWOZCWQOTXUHROWQQSGHLHRAWIWWUHIQROLZLUGNQRBGHLSIHFQFVKUTWVGHLUCGXADBJUNUSYBEDHKLABGZYUDBJVIWVYUVGDAVTLQULLHFCBIWVGPMWVKLWPOTMMYSXXWQSLIZXG'],
            "answer": "ALLRIGHTALLRIGHTBUTAPARTFROMBETTERSANITATIONANDMEDICINEANDEDUCATIONANDIRRIGATIONANDPUBLICHEALTHANDROADSANDAFRESHWATERSYSTEMANDBATHSANDPUBLICORDERWHATHAVETHEROMANSEVERDONEFORUS",
            "explanation": "GUIDO",
        },
        {
            "input": ['NOBODYEXPECTSTHESPANISHINQUISITION', 'PVFQNGSZWIEDAHJLWRKVWUOMPACWUPXKYV',
                      'QBVGHXSTAWFOAQTPFGIWICZEPKXDCSPKXOZAKYNVNSNSSYEVWOHKKXIHKCIVSUWFSEEUQBIPRKXQHKHXKFMGRPRGVMGULEUSTMFVQKXIHGKRQCMBULSHRCAQBVVOLWQBWEYUDCUCCXLWTYIRBMGUPFNILFCIEPNIKHBPCXLKJLVGKAWPTSUDXFQMIUCQCPZXJOASYVYNNJSEVRUSLSTHFNOLFCDFCMSGKUGJKZHGYIFKKQQBRVKVQAALGIIFGHTQCQHKCIDYWB'],
            "answer": "OUREXPERTSDESCRIBEYOUASANAPPALLINGLYDULLFELLOWUNIMAGINATIVETIMIDLACKINGININITIATIVESPINELESSEASILYDOMINATEDNOSENSEOFHUMOURTEDIOUSCOMPANYANDIRREPRESSIBLYDRABANDAWFULANDWHEREASINMOSTPROFESSIONSTHESEWOULDBECONSIDERABLEDRAWBACKSINCHARTEREDACCOUNTANCYTHEYAREAPOSITIVEBOON",
            "explanation": "CHECKIO",
        },
        {
            "input": [
                'OUREXPERTSDESCRIBEYOUASANAPPALLINGLYDULLFELLOWUNIMAGINATIVETIMIDLACKINGININITIATIVESPINELESSEASILYDOMINATEDNOSENSEOFHUMOURTEDIOUSCOMPANYANDIRREPRESSIBLYDRABANDAWFULANDWHEREASINMOSTPROFESSIONSTHESEWOULDBECONSIDERABLEDRAWBACKSINCHARTEREDACCOUNTANCYTHEYAREAPOSITIVEBOON',
                'XOJXCJRANKWJMPACTXDIHJMSGFJCJFDBSAYHXMEQZRUFGPZHVVUYBSUGRPWMNGVMFSVPCAPCFBSCGRULBAYFYCFXQYFBYSLNFLMIEBSUGNXFHXYABYGYMOZXOJMJXVXOKVTGCJHQTSXVALWIWYFBCTEDXEJVSGIUJOODTSXJQYJXFMVWGGLYJEXZWLXCBWMLAJMRFIMEIVRLIFLNXRAUTEJXEJQTTHEFRHUAFLGNLWWFWPXOFMFHPHNZXDUENUHHXCGRPWUTIA',
                'WITHISRGJWVYMGQYKIFHVBBAGVOVBCLBTH'],
            "answer": "NOBODYEXPECTSTHESPANISHINQUISITION",
            "explanation": "JUSTFUN",
        },
        {
            "input": [
                'ALLRIGHTALLRIGHTBUTAPARTFROMBETTERSANITATIONANDMEDICINEANDEDUCATIONANDIRRIGATIONANDPUBLICHEALTHANDROADSANDAFRESHWATERSYSTEMANDBATHSANDPUBLICORDERWHATHAVETHEROMANSEVERDONEFORUS',
                'OZZFWUVHOZZFWUVHPIHODOFHTFCAPSHHSFGOBWHOHWCBOBRASRWQWBSOBRSRIQOHWCBOBRWFFWUOHWCBOBRDIPZWQVSOZHVOBRFCORGOBROTFSGVKOHSFGMGHSAOBRPOHVGOBRDIPZWQCFRSFKVOHVOJSHVSFCAOBGSJSFRCBSTCFIG',
                'WHGBCHDWBWBUWHGDOGGSRCBHVWGDOFFCHWGBCACFSWHVOGQSOGSRHCPSWHGSLDWFSROBRUCBSHCASSHWHGAOYSFHVWGWGOZOHSDOFFCHWHGOGHWTTPSFSTHCTZWTSWHFSGHGWBDSOQSWTMCIVORBHBOWZSRWHHCHVSDSFQVWHKCIZRPSDIGVWBUIDHVSROWGWSGWHGFIBURCKBHVSQIFHOWBOBRXCWBSRHVSQVCWFWBJWGWPZSHVWGWGOBSLDOFFCH'],
            "answer": "ITSNOTPININGITSPASSEDONTHISPARROTISNOMOREITHASCEASEDTOBEITSEXPIREDANDGONETOMEETITSMAKERTHISISALATEPARROTITSASTIFFBEREFTOFLIFEITRESTSINPEACEIFYOUHADNTNAILEDITTOTHEPERCHITWOULDBEPUSHINGUPTHEDAISIESITSRUNGDOWNTHECURTAINANDJOINEDTHECHOIRINVISIBLETHISISANEXPARROT",
            "explanation": "OOOOOOO",
        },
        {
            "input": ['HESNOTTHEMESSIAHHESAVERYNAUGHTYBOY', 'OSZBVHAVLALGZWHVOSZOCSYMUOBUOHFPVM',
                      'HBVRZOZUVCKOZODWUYACHPSWURIOASO'],
            "answer": "ANODSASGOODASAWINKTOABLINDBATEH",
            "explanation": "HOHOHOHO",
        },
        {
            "input": [
                'IMALUMBERJACKANDIMOKISLEEPALLNIGHTANDIWORKALLDAYICUTDOWNTREESISKIPANDJUMPILIKETOPRESSWILDFLOWERSIPUTONWOMENSCLOTHINGANDHANGAROUNDINBARS',
                'MHECSNPHPNVGBYORLKSFMJJFSSYPGRZEIHDLHDAFPLOOJHVCZAVHGMAIXICFGLQODTRLEXXKTDPZIFHRNVZWJUJZGDPJAVPTWSSXJRNMNSQQGGSKFJBJYRYLRLHOUMYIHZLCOUQ',
                'EIHEMXTRPWJQVRIWQEGJQGJFHHJCYMWDFFHLX'],
            "answer": "ANDNOWFORSOMETHINGCOMPLETELYDIFFERENT",
            "explanation": "EVERYBODY",
        },
        {
            "input": [
                'IMALUMBERJACKANDIMOKISLEEPALLNIGHTANDIWORKALLDAYICUTDOWNTREESISKIPANDJUMPILIKETOPRESSWILDFLOWERSIPUTONWOMENSCLOTHINGANDHANGAROUNDINBARS',
                'XKTSIZQCKQOPZYGKWZDIBZZRTNTSZAXEAAOASGPVFXPJEKOLXANARBLLMYSRHGLRWCPLWQIZEGEPYRIMIYSFHUBSRSAMPLFFXNNACALMFLBFRJHAVVCETURUPLZHFBJLWPBOPPL',
                'PLWUCJUMKZCZTRAPBTRMFWZRICEFRVUDXYSAI'],
            "answer": "ANDNOWFORSOMETHINGCOMPLETELYDIFFERENT",
            "explanation": "PYTHON",
        },
        {
            "input": ['HESNOTTHEMESSIAHHESAVERYNAUGHTYBOY', 'TSFGMFHUXKQGFBYTVRLYHSERLMITARKPBR',
                      'MBBWQMGTHMPOFTUUBXMMMPYBLPPNMCT'],
            "answer": "ANODSASGOODASAWINKTOABLINDBATEH",
            "explanation": "MONTY",
        },
        {
            "input": [
                'ALLRIGHTALLRIGHTBUTAPARTFROMBETTERSANITATIONANDMEDICINEANDEDUCATIONANDIRRIGATIONANDPUBLICHEALTHANDROADSANDAFRESHWATERSYSTEMANDBATHSANDPUBLICORDERWHATHAVETHEROMANSEVERDONEFORUS',
                'GFTUWMBBDZRLQJVZVCWOVUZWTXIUESZNMUGGHQWOZCWQOTXUHROWQQSGHLHRAWIWWUHIQROLZLUGNQRBGHLSIHFQFVKUTWVGHLUCGXADBJUNUSYBEDHKLABGZYUDBJVIWVYUVGDAVTLQULLHFCBIWVGPMWVKLWPOTMMYSXXWQSLIZXG',
                'ONAQCZJQQWTAQWGVUAVSJIVWVOMXDFXIBLGTIURFKCBKOYWMDGKXBRPKCBVSDJQUSJUVGUUHMWCSYMWWZMUDYKLBKWYCADZGNMSOXLWWWZMIVHOZNESXYNWCLFQISONZHGZMQQDKUKHWLSWXVGXVWBGCTHRONBRHNYXHFIBQWKUOTGPKJCVVOHOXDZBMGOOMQHGONAUITALRKTNPHQALBDWTUVGXUCVHRZBMFVUCZLBBCALPRYBKWYCADBKRXDFXIB'],
            "answer": "ITSNOTPININGITSPASSEDONTHISPARROTISNOMOREITHASCEASEDTOBEITSEXPIREDANDGONETOMEETITSMAKERTHISISALATEPARROTITSASTIFFBEREFTOFLIFEITRESTSINPEACEIFYOUHADNTNAILEDITTOTHEPERCHITWOULDBEPUSHINGUPTHEDAISIESITSRUNGDOWNTHECURTAINANDJOINEDTHECHOIRINVISIBLETHISISANEXPARROT",
            "explanation": "GUIDO",
        },
        {
            "input": [
                'OUREXPERTSDESCRIBEYOUASANAPPALLINGLYDULLFELLOWUNIMAGINATIVETIMIDLACKINGININITIATIVESPINELESSEASILYDOMINATEDNOSENSEOFHUMOURTEDIOUSCOMPANYANDIRREPRESSIBLYDRABANDAWFULANDWHEREASINMOSTPROFESSIONSTHESEWOULDBECONSIDERABLEDRAWBACKSINCHARTEREDACCOUNTANCYTHEYAREAPOSITIVEBOON',
                'QBVGHXSTAWFOAQTPFGIWICZEPKXDCSPKXOZAKYNVNSNSSYEVWOHKKXIHKCIVSUWFSEEUQBIPRKXQHKHXKFMGRPRGVMGULEUSTMFVQKXIHGKRQCMBULSHRCAQBVVOLWQBWEYUDCUCCXLWTYIRBMGUPFNILFCIEPNIKHBPCXLKJLVGKAWPTSUDXFQMIUCQCPZXJOASYVYNNJSEVRUSLSTHFNOLFCDFCMSGKUGJKZHGYIFKKQQBRVKVQAALGIIFGHTQCQHKCIDYWB',
                'PVFQNGSZWIEDAHJLWRKVWUOMPACWUPXKYV'],
            "answer": "NOBODYEXPECTSTHESPANISHINQUISITION",
            "explanation": "CHECKIO",
        },
        {
            "input": ['NOBODYEXPECTSTHESPANISHINQUISITION', 'WITHISRGJWVYMGQYKIFHVBBAGVOVBCLBTH',
                      'XOJXCJRANKWJMPACTXDIHJMSGFJCJFDBSAYHXMEQZRUFGPZHVVUYBSUGRPWMNGVMFSVPCAPCFBSCGRULBAYFYCFXQYFBYSLNFLMIEBSUGNXFHXYABYGYMOZXOJMJXVXOKVTGCJHQTSXVALWIWYFBCTEDXEJVSGIUJOODTSXJQYJXFMVWGGLYJEXZWLXCBWMLAJMRFIMEIVRLIFLNXRAUTEJXEJQTTHEFRHUAFLGNLWWFWPXOFMFHPHNZXDUENUHHXCGRPWUTIA'],
            "answer": "OUREXPERTSDESCRIBEYOUASANAPPALLINGLYDULLFELLOWUNIMAGINATIVETIMIDLACKINGININITIATIVESPINELESSEASILYDOMINATEDNOSENSEOFHUMOURTEDIOUSCOMPANYANDIRREPRESSIBLYDRABANDAWFULANDWHEREASINMOSTPROFESSIONSTHESEWOULDBECONSIDERABLEDRAWBACKSINCHARTEREDACCOUNTANCYTHEYAREAPOSITIVEBOON",
            "explanation": "JUSTFUN",
        },
        {
            "input": [
                'ITSNOTPININGITSPASSEDONTHISPARROTISNOMOREITHASCEASEDTOBEITSEXPIREDANDGONETOMEETITSMAKERTHISISALATEPARROTITSASTIFFBEREFTOFLIFEITRESTSINPEACEIFYOUHADNTNAILEDITTOTHEPERCHITWOULDBEPUSHINGUPTHEDAISIESITSRUNGDOWNTHECURTAINANDJOINEDTHECHOIRINVISIBLETHISISANEXPARROT',
                'WHGBCHDWBWBUWHGDOGGSRCBHVWGDOFFCHWGBCACFSWHVOGQSOGSRHCPSWHGSLDWFSROBRUCBSHCASSHWHGAOYSFHVWGWGOZOHSDOFFCHWHGOGHWTTPSFSTHCTZWTSWHFSGHGWBDSOQSWTMCIVORBHBOWZSRWHHCHVSDSFQVWHKCIZRPSDIGVWBUIDHVSROWGWSGWHGFIBURCKBHVSQIFHOWBOBRXCWBSRHVSQVCWFWBJWGWPZSHVWGWGOBSLDOFFCH',
                'OZZFWUVHOZZFWUVHPIHODOFHTFCAPSHHSFGOBWHOHWCBOBRASRWQWBSOBRSRIQOHWCBOBRWFFWUOHWCBOBRDIPZWQVSOZHVOBRFCORGOBROTFSGVKOHSFGMGHSAOBRPOHVGOBRDIPZWQCFRSFKVOHVOJSHVSFCAOBGSJSFRCBSTCFIG'],
            "answer": "ALLRIGHTALLRIGHTBUTAPARTFROMBETTERSANITATIONANDMEDICINEANDEDUCATIONANDIRRIGATIONANDPUBLICHEALTHANDROADSANDAFRESHWATERSYSTEMANDBATHSANDPUBLICORDERWHATHAVETHEROMANSEVERDONEFORUS",
            "explanation": "OOOOOOO",
        },
        {
            "input": ['ANODSASGOODASAWINKTOABLINDBATEH', 'HBVRZOZUVCKOZODWUYACHPSWURIOASO',
                      'OSZBVHAVLALGZWHVOSZOCSYMUOBUOHFPVM'],
            "answer": "HESNOTTHEMESSIAHHESAVERYNAUGHTYBOY",
            "explanation": "HOHOHOHO",
        },
        {
            "input": ['ANDNOWFORSOMETHINGCOMPLETELYDIFFERENT', 'EIHEMXTRPWJQVRIWQEGJQGJFHHJCYMWDFFHLX',
                      'MHECSNPHPNVGBYORLKSFMJJFSSYPGRZEIHDLHDAFPLOOJHVCZAVHGMAIXICFGLQODTRLEXXKTDPZIFHRNVZWJUJZGDPJAVPTWSSXJRNMNSQQGGSKFJBJYRYLRLHOUMYIHZLCOUQ'],
            "answer": "IMALUMBERJACKANDIMOKISLEEPALLNIGHTANDIWORKALLDAYICUTDOWNTREESISKIPANDJUMPILIKETOPRESSWILDFLOWERSIPUTONWOMENSCLOTHINGANDHANGAROUNDINBARS",
            "explanation": "EVERYBODY",
        },
    ]
}
